### ISSUE TITLE
Invalid JSON Format: event

### ISSUE THREAD

**Issue by GeoffreyPlitt** [michaelcarter/mixpanel-data-export-js#29]
I am calling the "events" function with this params object:
```
{
      event: 'finishedWatching',
      type: 'general',
      interval: 90
  }
```

And I am getting an error I don't understand: `Invalid JSON Format: event`

Full error stack:
```
Error: Invalid JSON Format: event
    at mixpanel_exporter.events.data (/Users/giro/stardust-insights/api/index.js:161:36)
    at /Users/giro/stardust-insights/node_modules/mixpanel-data-export/src/mixpanel_data_export.js:115:16
    at request.onload (/Users/giro/stardust-insights/node_modules/mixpanel-data-export/src/mixpanel_data_export.js:146:7)
    at dispatchEvent (/Users/giro/stardust-insights/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/Users/giro/stardust-insights/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:614:14)
    at IncomingMessage.<anonymous> (/Users/giro/stardust-insights/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by hdemirev** [comment]
The event property should actually be an array of event names, per [Mixpanel's data export documentation](https://mixpanel.com/help/reference/data-export-api#libs-js), so it would look like: 

```
{
      event: ['finishedWatching'],
      type: 'general',
      interval: 90
}
```

**Comment by GeoffreyPlitt** [comment]
Will try that, thanks!
